version: '3.9'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wp_db
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: mysql_password
  php:
    image: bitnami/php-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - ./data:/app
    depends_on:
      - mysql
  apache:
    image: bitnami/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./config:/vhosts/myapp.conf:ro
      - ./data:/app
    depends_on:
      - php
  pureftp:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./data:/home/elyas
      - ./ftp/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "use your machine ip add"
      FTP_USER_NAME: ftp
      FTP_USER_PASS: ftp
      FTP_USER_HOME: set you path that you want to share with ftp #### Example =>     /home/root
    restart: always
